name: k_means_cluster
description: A simple library for partitioning small to medium data sets into clusters using the k-means clustering algorithm.
version: 0.3.0
homepage: https://github.com/ram6ler/k-means-cluster

environment:
  sdk: '>=3.0.0 <4.0.0'

