name: k_means_cluster
description: A simple implementation of k-means clustering.
version: 0.2.0
homepage: https://bitbucket.org/ram6ler/knn-cluster/wiki/Home
author: Richard Ambler <rambler@ibwya.net>

environment:
  sdk: '>=2.0.0 <3.0.0'

